### ISSUE TITLE
Sometimes, Failed to run Wits with follow error message.

### ISSUE THREAD

**Issue by pwsses** [Samsung/Wits#4]
When I run Wits, sometimes failed with follow error message.
...
events.js:183
throw er; // Unhandled 'error' event
^

Error: listen EADDRINUSE :::8888
at Server.setupListenHandle [as _listen2] (net.js:1360:14)
at listenInCluster (net.js:1401:12)
at Server.listen (net.js:1485:7)
at ChildProcess.exithandler (child_process.js:268:7)
at emitTwo (events.js:126:13)
at ChildProcess.emit (events.js:214:7)
at maybeClose (internal/child_process.js:915:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Wits@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Wits@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
...

**Comment by pwsses** [comment]
When nodeJS server is already running in your PC this error message is occur. Sometimes Wits run on git bash, thie error is occur because git bash didn't destroy nodeJS server. please check your run TaskManager in PC. If you find nodeJS process, close it.
