### ISSUE TITLE
ReferenceError when connecting to TV

### ISSUE THREAD

**Issue by TrebuhD** [Samsung/Wits#63]
I'm getting the following error when attempting to connect to my TV:

```
 <user>@MacBook-Pro  ~/workspace/Empty  wits -s
 _      ____________
| | /| / /  _/_  __/__
| |/ |/ // /  / / (_-<
|__/|__/___/ /_/ /___/

Start running Wits............

      > [ Stored Information ]

      > baseAppPath  : /Users/<user>/workspace/Empty
      > width        : 1920
      > deviceIp     : 192.168.1.65
      > socketPort   : 26101
      > isDebugMode  : true

      > profile path : /Users/<user>/tizen-studio-data/profile/profiles.xml
      > hostIp       : 192.168.1.67

connect to....192.168.1.65
Success to connect 192.168.1.65
(node:22068) UnhandledPromiseRejectionWarning: ReferenceError: deviceIpAddress is not defined
    at Object.getDeviceName (/Users/<user>/.nvm/versions/node/v12.18.3/lib/node_modules/@tizentv/wits/lib/deviceConnectHelper.js:49:17)
    at Object.getConnectedDeviceInfo (/Users/<user>/.nvm/versions/node/v12.18.3/lib/node_modules/@tizentv/wits/lib/deviceConnectHelper.js:13:47)
    at Object.getDeviceInfo (/Users/<user>/.nvm/versions/node/v12.18.3/lib/node_modules/@tizentv/wits/lib/userInfoHelper.js:69:42)
    at Object.run (/Users/<user>/.nvm/versions/node/v12.18.3/lib/node_modules/@tizentv/wits/command/start.js:38:49)
    at Object.<anonymous> (/Users/<user>/.nvm/versions/node/v12.18.3/lib/node_modules/@tizentv/wits/lib/cli.js:31:18)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
(node:22068) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:22068) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Tizen studio shows a TV connected at this IP address:
![image](https://user-images.githubusercontent.com/7022085/92377856-181e7080-f105-11ea-963c-ec0d11e1deb2.png)

I tried changing the port number, but it made no difference.

It all works well when running on a Tizen simulator on the same device.

**Comment by pwsses** [comment]
Hello Thank you for issue report.
We will check this issue and reply to you.

**Comment by prozanne** [comment]
Hi!
You don't have to change socket port number like "> socketPort   : 26101".
26101 port is for chrome inspector port, and It's different port which WITs is connecting to TV.
Usually we make a port randomly.
We will check more about this issue but could you please check if another "sdb" is running on the task manager?
If do so, please terminate previous "sdb" and just try "wits -s" without opening Tizen Studio.

**Comment by prozanne** [comment]
Hi 👍 
This issue has been resolved.
please update WITs to v2.3.4.
