### ISSUE TITLE
Failed to uninstall wits

### ISSUE THREAD

**Issue by needz** [Samsung/Wits#88]
Can anyone help me solve this issue? I have already tried full TV reset, but it doesn't help. There is no Wits installed on TV.

Wits 2.4.7
macOS Big Sur 11.1
Tizen 5.5 TV

Start running Wits............

[@tizentv/tools]tools.getToolPath: toolName = sdb

      > [ Stored Information ]

      > baseAppPath  : /........
      > width        : 1920
      > deviceIp     : 192.168.0.121
      > isDebugMode  : true

      > profile path : /usr/local/lib/node_modules/@tizentv/wits/resource/profiles.xml
      > hostIp       : 192.168.0.100

connect to....192.168.0.121
Success to connect 192.168.0.121
content src is : index.html

Start packaging Samsung Tizen TV Platform......

[webide-common-tizentv]projectHelper.buildWidget() profilePath = /usr/local/lib/node_modules/@tizentv/wits/resource/profiles.xml, excludeFiles = undefined
After build package, signature tempory files were removed
[webide-common-tizentv]projectHelper.widget.on(): Build Package completed!
============================== Build Package completed!

============================== Start to install the package

[warning] Failed to uninstall Wits

Failed to install Wits

**Comment by prozanne** [comment]
Hi :)

"Failed to uninstall Wits" is not a fatal issue, actually It's just a warning that you don't need to care.
The main cause could be different thing.
First, would you please check the developer mode was set on TV?
And have you tried WITs before? or It's your first time?

Thanks,
Rosie

**Comment by needz** [comment]
@prozanne Developer mode is set correctly, I have used WITs before on the same TV. Tizen Studio 4.1 works fine and I can install packages through Tizen Studio, but not with WITs.

**Comment by prozanne** [comment]
Hi again, I guess it might have a problem with a certification.
If you already have Tizen Studio, could you try creating a certification via IDE and setting profile path of WITs to the path of Tizen Studio certification?

Thanks.

**Comment by needz** [comment]
@prozanne When I tried your steps and run WITs directly in command line, here's what I have got (this certificate profile works with Tizen Studio):

```
Start running Wits............

[@tizentv/tools]tools.getToolPath: toolName = sdb

      > [ Stored Information ]

      > baseAppPath  : /***/***/
      > width        : 1280
      > deviceIp     : 192.168.0.123
      > isDebugMode  : true

      > profile path : /***/***/tizen-studio-data/profile/profiles.xml
      > hostIp       : 192.168.0.100

connect to....192.168.0.123
Success to connect 192.168.0.123
closed
Failed to getDeviceInfo: Error: Command failed: /***/***/tizentv-tools/sdb/sdb -s 192.168.0.123:26101 capability
closed

content src is : index.html

Start packaging Samsung Tizen TV Platform......

[webide-common-tizentv]projectHelper.buildWidget() profilePath = /Users/needz/tizen-studio-data/profile/profiles.xml, excludeFiles = undefined
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
(node:29055) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'privateKey' of null
    at PackageSigner.signPackage (/usr/local/lib/node_modules/@tizentv/wits/node_modules/@tizentv/webide-common-tizentv/lib/packageSigner.js:180:48)
    at /usr/local/lib/node_modules/@tizentv/wits/node_modules/@tizentv/webide-common-tizentv/lib/projectHelper.js:117:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:29055) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:29055) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When I try it through VSCode, it just overwrites the Profiles path to VSCODE's extension.

**Comment by prozanne** [comment]
Hi,

If you don't mind could you please share the "sdk_toolpath" value?
Please type directly "/***/***/tizentv-tools/sdb/sdb -s 192.168.0.123:26101 capability" at the command line.

Thanks.

**Comment by needz** [comment]
@prozanne , here you go:

```
secure_protocol:enabled
intershell_support:disabled
filesync_support:pushpull
usbproto_support:disabled
sockproto_support:enabled
syncwinsz_support:enabled
sdbd_rootperm:disabled
rootonoff_support:disabled
encryption_support:disabled
zone_support:disabled
multiuser_support:enabled
cpu_arch:armv7
sdk_toolpath:/home/owner/share/tmp/sdk_tools
profile_name:tv
vendor_name:Samsung
can_launch:tv-samsung
device_name:Tizen
platform_version:5.0
product_version:4.0
sdbd_version:2.2.31
sdbd_plugin_version:3.7.1_TV_REL
sdbd_cap_version:1.0
log_enable:disabled
log_path:/tmp
appcmd_support:disabled
appid2pid_support:enabled
pkgcmd_debugmode:enabled
netcoredbg_support:enabled
```

**Comment by prozanne** [comment]
Hmmm, Actually according to your log, It seems to fail to get capabillity, so I asked it you.

The weird points are "closed" in your log.
"closed
Failed to getDeviceInfo: Error: Command failed: /***/***/tizentv-tools/sdb/sdb -s 192.168.0.123:26101 capability
closed"

WITs is also using sdb, and we are not working for Tizen Studio, so I don't know why "closed" is showing exactly.
Well, I will try to find a way.

At your side, could you please follow this step again?
Just for checking if it works fine. I know you've used it before, but development environment is so sensitive.

At the Tizen Studio,
1. Create Samsung certification (Public / Partner)
2. Push your certification to your target
You can refer below guide of Tizen Studio. (Search "Permit to install applications")
https://developer.samsung.com/smarttv/develop/getting-started/using-sdk/command-line-interface.html

3. Create a basicProject
4. Run as
5. If you succeed to do this step, Go to WITs cli
6. wits --init
7. Put profile path to the profiles.xml from Tizen Studio.
8. wits --start

Thanks.

**Comment by needz** [comment]
@prozanne , I did all the steps and I successfully launched BasicProject (TV 5.5) on TV using Tizen Studio, but it failed in WITs again.

```
Start running Wits............

[@tizentv/tools]tools.getToolPath: toolName = sdb

      > [ Stored Information ]

      > baseAppPath  : /***/BasicProject
      > width        : 1920
      > deviceIp     : 192.168.0.123
      > isDebugMode  : false

      > profile path : /Users/***/tizen-studio-data/profile/profiles.xml
      > hostIp       : 192.168.0.100

connect to....192.168.0.123
Success to connect 192.168.0.123
content src is : index.html

Start packaging Samsung Tizen TV Platform......

[webide-common-tizentv]projectHelper.buildWidget() profilePath = /Users/***/tizen-studio-data/profile/profiles.xml, excludeFiles = undefined
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
(node:78142) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'privateKey' of null
    at PackageSigner.signPackage (/usr/local/lib/node_modules/@tizentv/wits/node_modules/@tizentv/webide-common-tizentv/lib/packageSigner.js:180:48)
    at /usr/local/lib/node_modules/@tizentv/wits/node_modules/@tizentv/webide-common-tizentv/lib/projectHelper.js:117:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:78142) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:78142) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
